services:
  db:
    image: ghcr.io/ruc-msc-cs-cit-2024/portfolio_subproject_1:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: bash -c "[ -f /tmp/startup_finished ]"
      interval: 5s
      timeout: 5s
      retries: 60
  api:
    image: ghcr.io/ruc-msc-cs-cit-2024/portfolio_subproject_2:latest
    ports:
      - 5000:8080
      - 5001:8043
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8043;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=postgres;Username=postgres;Password=postgres
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      db:
        condition: service_healthy 
  frontend:
    image: ghcr.io/ruc-msc-cs-cit-2024/portfolio_subproject_3
    ports:
      - 3000:3030
    environment: 
      - MY_APP_API_BASE_URL=https://localhost:5001/api/
      - MY_APP_TMDB_BASE_URL=https://api.themoviedb.org/3/
      - MY_APP_TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p/
      - MY_APP_TMDB_READ_TOKEN=${MY_APP_TMDB_READ_TOKEN}
    depends_on:
      - api

